# Generated by Django 4.2.24 on 2025-11-11 12:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessIdea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=200)),
                ('business_description', models.TextField()),
                ('industry', models.CharField(max_length=100)),
                ('target_market', models.CharField(max_length=200)),
                ('initial_investment', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MarketAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_size', models.CharField(max_length=200)),
                ('growth_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('competition_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=50)),
                ('target_demographics', models.TextField()),
                ('market_trends', models.TextField()),
                ('opportunities', models.TextField()),
                ('threats', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business_idea', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='market_analysis', to='business_planner.businessidea')),
            ],
        ),
        migrations.CreateModel(
            name='LocationRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('reasoning', models.TextField()),
                ('population', models.IntegerField(blank=True, null=True)),
                ('market_size', models.CharField(blank=True, max_length=100, null=True)),
                ('business_idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='business_planner.businessidea')),
            ],
            options={
                'ordering': ['-score'],
            },
        ),
        migrations.CreateModel(
            name='DomainSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(max_length=200)),
                ('is_available', models.BooleanField(default=False)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('business_idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='business_planner.businessidea')),
            ],
        ),
        migrations.CreateModel(
            name='BusinessPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('executive_summary', models.TextField()),
                ('market_analysis', models.TextField()),
                ('organization_structure', models.TextField()),
                ('products_services', models.TextField()),
                ('marketing_strategy', models.TextField()),
                ('financial_projections', models.TextField()),
                ('success_probability', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_idea', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_plan', to='business_planner.businessidea')),
            ],
        ),
    ]
